# ------------------------------------- 
# Based on
# -------------------------------------
FROM postgres:14

#-------------------------------------
# INFO
# -------------------------------------
LABEL author="Alberto Serra"
LABEL author_nickname=""
LABEL project="Flask Registration Login API - local"
LABEL version = "1.0.0"

# -------------------------------------
# Packages
# -------------------------------------
# RUN apt-get update && \
#      apt-get install postgresql-13 -y

# -------------------------------------
# Add Postrgres INIT
# -------------------------------------
ADD ./ ./